platform:
  - x64
  - x86

environment:
  matrix:
    - RUST_VERSION: 1.3.0
      VENDOR: gnu
    - RUST_VERSION: 1.3.0
      VENDOR: msvc
    - RUST_VERSION: beta
      VENDOR: gnu
    - RUST_VERSION: beta
      VENDOR: msvc

install:
  - ps: |
      if ($env:PLATFORM -eq "x86") {
          $arch = "i686"
      }
      else {
          $arch = "x86_64"
      }
      Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-$arch-pc-windows-${env:VENDOR}.exe" -FileName rust-install.exe
  - rust-install.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
