[package]

name = "serial"
version = "0.1.1"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Rust library for accessing serial ports."
license = "MIT"
homepage = "https://github.com/dcuddeback/serial-rs"
repository = "https://github.com/dcuddeback/serial-rs.git"

[dependencies]
libc = "0.1.8"
time = "0.1.25"

[target.aarch64-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.arm-unknown-linux-gnueabi.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.arm-unknown-linux-gnueabihf.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.i686-apple-darwin.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.i686-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.mips-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.mipsel-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.powerpc-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.x86_64-apple-darwin.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.x86_64-unknown-dragonfly.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.x86_64-unknown-freebsd.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.x86_64-unknown-linux-gnu.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"

[target.x86_64-unknown-openbsd.dependencies]
termios = "0.1.0"
ioctl-rs = "0.1.1"
