[package]

name = "serial"
version = "0.0.1"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]
description = "Rust library for accessing serial ports."
license = "MIT"
homepage = "https://github.com/dcuddeback/serial-rs"
repository = "https://github.com/dcuddeback/serial-rs.git"

[dependencies]
termios = "0.0.3"
