[package]
name = "serial-unix"
version = "0.4.0"
authors = ["David Cuddeback <david.cuddeback@gmail.com>"]

[dependencies]
serial-core = { path = "../serial-core" }
libc = "0.2.1"
termios = "0.2.2"
ioctl-rs = "0.1.5"
